heshammourad/vexillology-contests

- server/index.js
> Load contests based on  env_level

- server/imgur.js
- server/index.js
> Handle missing images in entries table

- server/imgur.js
> Replace Imgur API with commerical Rapid API

- server/index.js
> Properly load image data from both database and API

- server/index.js
> Handle many-to-many relationship between contests and entries

- react-ui/src/pages/contests/Contests.jsx
> Remove contests list subheader

- package-lock.json
- package.json
- server/db.js
- server/imgur.js
- server/index.js
- server/logger.js
- server/memcache.js
- server/reddit.js
> Add server-side logging

- react-ui/src/pages/contest/Contest.jsx
- react-ui/src/pages/entry/Entry.jsx
- react-ui/src/pages/entry/NavigateIconButton.jsx
> Add entry navigation

- react-ui/src/pages/entry/Entry.jsx
> Make navigation arrows visible for three seconds on load

- react-ui/src/components/CustomIconButton.jsx
- react-ui/src/pages/entry/Entry.jsx
> Add key handlers for entry page buttons

- react-ui/src/common/useSwrData.jsx
- react-ui/src/components/FiveStar.jsx
- react-ui/src/pages/contest/Contest.jsx
- server/index.js
- server/memcache.js
> Align new voting controls to bottom of cards

- react-ui/src/components/LazyLoadCardImage.jsx
- react-ui/src/components/VotingSnackbar.jsx
- react-ui/src/pages/contest/CardImageLink.jsx
- react-ui/src/pages/contest/Contest.jsx
- server/index.js
> Add winners view for local voting contests

- react-ui/src/pages/contest/Contest.jsx
> Fix categories not sticking on navigation

- server/api/images.js
Reverts heshammourad/vexillology-contests#222
Not enough cache room in memcache to support this. Will need to try a different approach
> Revert "Cache image data in memcache"

- react-ui/src/pages/submission/Submission.jsx
- Improper spacing
- Entries not showing up in table
> Fix submission bugs

- react-ui/src/common/useSwrMutation.jsx
- react-ui/src/components/VotingSlider.jsx
Updated to properly handle case where the API to update the data differs from the key to mutate
> Fix voting mutation error

- react-ui/src/pages/reviewSubmissions/ReviewSubmissions.jsx
- react-ui/src/pages/reviewSubmissions/StatusFilters.jsx
On the review page, there are 4 pills for each of the statuses. This will add a count to the pill label, e.g. "Pending (8)" if there are any of that status.
> Add submission status count to filter pill label

- react-ui/src/components/MenuItemLink.jsx
I saw a proptype error unrelated to your changes when reviewing it, so added it to a separate PR.
> Fix MenuItemLink PropTypes

- react-ui/src/components/AccountMenu.jsx
- react-ui/src/env.js
- server/env.js
Here's the fix. I also added a couple of eslint rules.
> Put default value when destructuring

- server/api/contest.js
> Refresh materialized view when fetching contest results for the first time

- .env.template
- react-ui/src/components/DevBar.jsx
- react-ui/src/pages/entry/EntryAppBarMain.jsx
- react-ui/src/pages/entry/EntryModal.jsx
- react-ui/src/pages/submission/SubmissionForm.jsx
EntryModal now shows what flag number you are on while voting.
> Character limits on title and description (bonus: flag count)

- react-ui/src/pages/contest/Contest.jsx
Uses `isValidating` to ensure the contest data is up-to-date. Critical to prevent navigation to submission closed page when contest is already in the voting stage.
> Preventing cache from displaying wrong contest info

- react-ui/src/pages/analyzeVotes/AnalyzeVotes.jsx
1. Redirect user to the most recent / current contest.
2. Fix left-right / up-down arrow key description
> Fixes to analyze voting

- react-ui/src/pages/contests/Contests.jsx
- react-ui/src/pages/submission/ContestRules.jsx
Minor change to change the contest width, doesn't need to be that wide.
> Contest rules width

- server/api/authentication.js
- server/db/index.js
- server/db/userPermissions.js
- server/index.js
Apply control to posting submissions
> Add role-based access control and user permissions management

- react-ui/src/components/EntryDescriptionDrawer.jsx
- react-ui/src/pages/contest/ContestAppBarMain.jsx
- react-ui/src/pages/contest/ContestGrid.jsx
Fixed bug where voting status was relying on deprecated isContestMode
> swapped isContestMode for contestStatus

- .cursorrules
- react-ui/src/App.jsx
- react-ui/src/components/ContestRemindersAlert.jsx
- react-ui/src/components/index.js
- react-ui/src/pages/settings/Settings.jsx
As requested by mod team.
Alert for the contest reminders breaking changes.
It's tall, but dismissable so should not be a problem.
> Contest Reminders Alert

- server/api/contest/index.js
Found that the reddit contest is looking at vote dates and stuff that's only relevant to site contests, so had it return early to avoid all that.
> Return reddit contest without processing further
